// public class DebugMe {
//     public static void main(String[] args) {
//        int books; // declare variable
//        System.out.print("The number of books is ");
       
//        10 = books; // initialize variable
//        System.out.println(books); // print value of variable
//     }
//  }
 
public class DebugMe {
    public static void main(String[ ] args) {
        int books;
        System.out.print("The number of books is ");
        10 = books;
        System.out.println(books);
    }
}